server {
    listen 80;
    root /var/www/html;
    index FLBB_Zuschauer_Zahlen.php;

    location / {
        try_files $uri $uri/ /FLBB_Zuschauer_Zahlen.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index FLBB_Zuschauer_Zahlen.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
